services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      BETFAIR_USERNAME: ${BETFAIR_USERNAME}
      BETFAIR_PASSWORD: ${BETFAIR_PASSWORD}
      BETFAIR_APPLICATION_KEY: ${BETFAIR_APPLICATION_KEY}
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /Users/michael/Documents/Football:/data
      - /Users/michael/Documents/Betfair:/betfair

volumes:
  postgres_data:
