# Generated by Django 5.1 on 2024-08-13 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('team_type', models.CharField(choices=[('club', 'Club'), ('national', 'National')], max_length=20)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='teams', to='football.country')),
                ('league_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='league_teams', to='football.country')),
                ('confederation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='teams', to='football.confederation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'teams',
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('what_3_words', models.CharField(max_length=200, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='venues', to='football.country')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'venues',
            },
        ),
    ]
