# Generated by Django 5.1 on 2024-08-13 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_team_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'metric_types',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('kickoff', models.DateTimeField()),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='games', to='football.stage')),
                ('venue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='games', to='football.venue')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'games',
            },
        ),
        migrations.CreateModel(
            name='GameTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_teams', to='football.game')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='game_teams', to='football.team')),
                ('half_time_score', models.IntegerField(null=True)),
                ('full_time_score', models.IntegerField(null=True)),
                ('after_extra_time_score', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'game_teams',
            },
        ),
        migrations.CreateModel(
            name='GameTeamMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_team_metrics', to='football.gameteam')),
                ('metric_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='game_team_metrics', to='football.metrictype')),
                ('value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'game_metrics',
            },
        ),
    ]
