# Generated by Django 5.1 on 2024-08-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0004_manager_team_unique_team_name_country_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='competition',
            constraint=models.UniqueConstraint(fields=('name', 'gender', 'country'), name='unique_competition_name_gender_country'),
        ),
        migrations.AddConstraint(
            model_name='gameteam',
            constraint=models.UniqueConstraint(fields=('number', 'game'), name='unique_number_game'),
        ),
        migrations.AddConstraint(
            model_name='gameteam',
            constraint=models.UniqueConstraint(fields=('game', 'team'), name='unique_game_team'),
        ),
        migrations.AddConstraint(
            model_name='season',
            constraint=models.UniqueConstraint(fields=('name', 'competition'), name='unique_season_name_competition'),
        ),
        migrations.AddConstraint(
            model_name='stage',
            constraint=models.UniqueConstraint(fields=('name', 'season'), name='unique_stage_name_season'),
        ),
        migrations.AddConstraint(
            model_name='venue',
            constraint=models.UniqueConstraint(fields=('name', 'country'), name='unique_venue_name_country'),
        ),
    ]
