# Generated by Django 5.1 on 2024-08-16 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0008_country_creation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterField(
            model_name='competition',
            name='competition_type',
            field=models.CharField(choices=[('domestic', 'DOMESTIC'), ('club_international', 'CLUB_INTERNATIONAL'), ('national', 'NATIONAL')], max_length=20),
        ),
        migrations.AlterField(
            model_name='competition',
            name='gender',
            field=models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], max_length=6),
        ),
        migrations.AlterField(
            model_name='team',
            name='gender',
            field=models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], max_length=6),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_type',
            field=models.CharField(choices=[('club', 'CLUB'), ('national', 'NATIONAL')], max_length=20),
        ),
        migrations.CreateModel(
            name='TeamExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to='football.team')),
                ('source', models.CharField(choices=[('football-data.co.uk', 'FOOTBALL_DATA')], max_length=200)),
                ('external_link_type', models.CharField(choices=[('id', 'ID'), ('url', 'URL'), ('name', 'NAME')], max_length=20, null=True)),
                ('value', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'team_external_links',
                'constraints': [models.UniqueConstraint(fields=('team', 'external_link_type', 'source', 'value'), name='unique_team_type_source_value')],
            },
        ),
    ]
