# Generated by Django 5.1 on 2024-10-06 09:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0012_alter_team_code_alter_team_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamexternallink',
            name='source',
            field=models.CharField(choices=[('football-data.co.uk', 'FOOTBALL_DATA'), ('Understat', 'UNDERSTAT'), ('FotMob', 'FOT_MOB')], max_length=200),
        ),
        migrations.CreateModel(
            name='GameTeamMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('football-data.co.uk', 'FOOTBALL_DATA'), ('Understat', 'UNDERSTAT'), ('FotMob', 'FOT_MOB')], max_length=200)),
                ('xg', models.DecimalField(decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(99.99)])),
                ('shots', models.IntegerField(null=True)),
                ('shots_on_target', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_team_metrics', to='football.gameteam')),
            ],
            options={
                'db_table': 'game_team_metrics',
                'constraints': [models.UniqueConstraint(fields=('game_team', 'source'), name='unique_game_team_source')],
            },
        ),
    ]
