# Generated by Django 5.1 on 2024-10-10 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0013_alter_teamexternallink_source_gameteammetric'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to='football.game')),
                ('source', models.CharField(choices=[('football-data.co.uk', 'FOOTBALL_DATA'), ('Understat', 'UNDERSTAT'), ('FotMob', 'FOT_MOB')], max_length=200)),
                ('external_link_type', models.CharField(choices=[('id', 'ID')], max_length=20, null=True)),
                ('value', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'game_external_links',
                'constraints': [models.UniqueConstraint(fields=('game', 'external_link_type', 'source', 'value'), name='unique_game_type_source_value')],
            },
        ),
    ]
