# Generated by Django 5.1 on 2024-10-11 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0015_stageteammetric'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to='football.competition')),
                ('source', models.CharField(choices=[('football-data.co.uk', 'FOOTBALL_DATA'), ('Understat', 'UNDERSTAT'), ('FotMob', 'FOT_MOB')], max_length=200)),
                ('external_link_type', models.CharField(choices=[('id', 'ID')], max_length=20, null=True)),
                ('value', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'competition_external_links',
                'constraints': [models.UniqueConstraint(fields=('competition', 'external_link_type', 'source'), name='unique_competition_type_source')],
            },
        ),
    ]
