# Generated by Django 5.1.1 on 2024-10-11 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0016_competitionexternallink'),
    ]

    operations = [
        migrations.CreateModel(
            name='StagePointsDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='stage_deductions', to='football.stage')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_deductions', to='football.team')),
                ('deduction', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'stage_points_deductions',
                'constraints': [models.UniqueConstraint(fields=('stage', 'team'), name='unique_stage_team')],
            },
        ),
    ]
